resolver: lts-18.15

allow-newer: true

packages:
- .

extra-deps:
- numhask-0.10.0.0
- numhask-space-0.10.0.0
- numhask-array-0.10.0
- formatn-0.2.0
- optics-core-0.4
- random-1.2.0
- chart-svg-0.3.0
